from pydantic import EmailStr

from samey.models import *


class User(SameyTextIdentified, SameyModel):
    first_name: constr(min_length=1, max_length=30, strip_whitespace=True) = ...
    last_name: constr(min_length=1, max_length=30, strip_whitespace=True) = ...
    email: EmailStr = ...
